layout_spectrum: 0.4707633
typography_spectrum: 0.3315606
color:
  saturation: 0.898932
  lightness: 0.5686602
  brandStrength: 0.1613205
  rhythmicContrast: 0.5030428
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: The After Party
